# Generated by Django 3.2.7 on 2021-09-22 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('img', models.URLField()),
                ('bio', models.CharField(max_length=200)),
                ('account_updated', models.DateField()),
                ('projects_count', models.IntegerField(default=0)),
                ('contributions_count', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('header', models.CharField(max_length=100)),
                ('img', models.URLField()),
                ('description', models.TextField()),
                ('private', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_updated', models.DateField()),
                ('admin_list', models.ManyToManyField(related_name='administrators', to='data_collective.Citizen')),
                ('contributor_list', models.ManyToManyField(related_name='contributors', to='data_collective.Citizen')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='data_collective.citizen')),
            ],
        ),
        migrations.CreateModel(
            name='DataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int1', models.IntegerField(blank=True, default=None)),
                ('int2', models.IntegerField(blank=True, default=None)),
                ('int3', models.IntegerField(blank=True, default=None)),
                ('int4', models.IntegerField(blank=True, default=None)),
                ('float1', models.FloatField(blank=True, default=None)),
                ('float2', models.FloatField(blank=True, default=None)),
                ('float3', models.FloatField(blank=True, default=None)),
                ('float4', models.FloatField(blank=True, default=None)),
                ('dropdown1', models.TextField(blank=True, default=None)),
                ('dropdown2', models.TextField(blank=True, default=None)),
                ('notes', models.TextField(blank=True, default=None)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9)),
                ('long', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9)),
                ('zipcode', models.IntegerField(blank=True, default=None)),
                ('date_created', models.DateField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entries', to='data_collective.citizen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='data_collective.project')),
            ],
        ),
    ]
