# Generated by Django 3.2.7 on 2021-09-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0002_auto_20210922_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='dropdown1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dropdown2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float1',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float2',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float3',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float4',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int4',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='zipcode',
            field=models.IntegerField(blank=True),
        ),
    ]
