# Generated by Django 3.2.7 on 2021-09-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0004_auto_20210923_1324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataentry',
            old_name='long',
            new_name='lon',
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dropdown1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='dropdown2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
