# Generated by Django 3.2.7 on 2021-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0005_auto_20210923_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataentry',
            name='img_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
