# Generated by Django 3.2.7 on 2021-09-23 16:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0006_dataentry_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='float1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float3',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='float4',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='int4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='dataentry',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ints', models.PositiveIntegerField(default=0)),
                ('floats', models.PositiveIntegerField(default=0)),
                ('img_url', models.BooleanField(default=False)),
                ('dropdowns', models.PositiveIntegerField(default=0)),
                ('dropdownOptions1', models.TextField(blank=True, default='')),
                ('dropdownOptions2', models.TextField(blank=True, default='')),
                ('notes', models.BooleanField(default=False)),
                ('latlon', models.BooleanField(default=False)),
                ('zipcode', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='forms', to='data_collective.citizen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form', to='data_collective.project')),
            ],
        ),
    ]
