# Generated by Django 3.2.7 on 2021-09-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0007_auto_20210923_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='dropdowns',
        ),
        migrations.RemoveField(
            model_name='form',
            name='floats',
        ),
        migrations.RemoveField(
            model_name='form',
            name='ints',
        ),
        migrations.AddField(
            model_name='form',
            name='dropdown1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='dropdown1_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='dropdown2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='dropdown2_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='float1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='float1_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='float2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='float2_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='float3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='float3_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='float4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='float4_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='img_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='int1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='int1_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='int2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='int2_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='int3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='int3_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='form',
            name='int4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='int4_label',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
