# Generated by Django 3.2.7 on 2021-09-27 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0009_auto_20210925_1823'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataVis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=100)),
                ('chart_title', models.CharField(max_length=100)),
                ('x_axis', models.CharField(max_length=100)),
                ('x_axis_min', models.IntegerField(null=True)),
                ('x_axis_max', models.IntegerField(null=True)),
                ('y_axis', models.CharField(max_length=100)),
                ('y_axis_min', models.IntegerField(null=True)),
                ('y_axis_max', models.IntegerField(null=True)),
                ('legend', models.BooleanField(default=True)),
                ('pie_hole', models.FloatField(null=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='citizen', to='data_collective.citizen')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_visualizations', to='data_collective.project')),
            ],
        ),
    ]
