# Generated by Django 3.2.7 on 2021-09-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0012_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
