# Generated by Django 3.2.7 on 2021-09-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0014_alter_dataentry_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataentry',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
