# Generated by Django 3.2.7 on 2021-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0016_alter_dataentry_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(default='guest', max_length=40),
            preserve_default=False,
        ),
    ]
