# Generated by Django 3.2.7 on 2021-09-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collective', '0017_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datavis',
            name='pie_hole',
        ),
        migrations.RemoveField(
            model_name='datavis',
            name='x_axis_max',
        ),
        migrations.RemoveField(
            model_name='datavis',
            name='x_axis_min',
        ),
        migrations.RemoveField(
            model_name='datavis',
            name='y_axis_max',
        ),
        migrations.RemoveField(
            model_name='datavis',
            name='y_axis_min',
        ),
        migrations.AlterField(
            model_name='datavis',
            name='chart_title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datavis',
            name='chart_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='datavis',
            name='x_axis',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='datavis',
            name='y_axis',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
